name: Release (Dev/Nightly)

on:
  push:
    paths:
      - src/**/*.css

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get current date
        id: date
        run: echo date=\"$(date +"%D at %r")\" >> $GITHUB_OUTPUT

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript and bundle into asar
        run: pnpm run build:dev:bundle

      - name: Clear latest nightly release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'bundle/*'
          makeLatest: true
          allowUpdates: true
          tag: nightly
          body: 'Generated on `${{ steps.date.outputs.date }}`'
          name: nightly
          generateReleaseNotes: true
          replacesArtifacts: true
          prerelease: true
